/* Generated by wayland-scanner 1.20.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif


static const struct wl_interface *my_extension_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message my_interface_requests[] = {
	{ "function1", "iiii", my_extension_types + 0 },
};

static const struct wl_message my_interface_events[] = {
	{ "onfunction1", "iiii", my_extension_types + 0 },
};

WL_PRIVATE const struct wl_interface my_interface_interface = {
	"my_interface", 1,
	1, my_interface_requests,
	1, my_interface_events,
};

